music_directory    "/home/dl/Music"
db_file            "/home/dl/.config/mpd/database"
log_file           "/home/dl/.config/mpd/log"
pid_file           "/home/dl/.config/mpd/pid"
state_file         "/home/dl/.config/mpd/state"

audio_output {
    type  "pulse"
    name  "PulseAudio Output"
}
